project_name: collector

release:
  name_template: "cat-github-metric-collector {{.Version}}"
  prerelease: auto

before:
  hooks:
    - go mod tidy
    - go fmt ./...

builds:
  - id: collector
    binary: "{{ tolower .Os }}-{{ .Arch }}/{{ .ProjectName }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    asmflags:
      - all=-trimpath={{.Env.WORKINGDIR}}
    gcflags:
      - all=-trimpath={{.Env.WORKINGDIR}}
    mod_timestamp: '{{ .CommitTimestamp }}'
    no_unique_dist_dir: true

archives:
  - format: binary
    name_template: "{{ tolower .Os }}-{{ .Arch }}"
    allow_different_binary_count: true

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-{{.ShortCommit}}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
