# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: release

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GO_VERSION: 1.18

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Relay: Install
      run: |
        export RELAY_DIR="${HOME}/relay"
        mkdir -p $RELAY_DIR
        curl -L https://github.com/puppetlabs/relay/releases/download/v5.2.0/relay-v5.2.0-linux-amd64 > $RELAY_DIR/relay
        echo $RELAY_DIR >> $GITHUB_PATH

    - name: Relay: Login
      run: echo $RELAY_TOKEN | relay auth login --stdin
      env:
        RELAY_TOKEN: ${{ secrets.RELAY_TOKEN }}

    - name: Workflow Builder: Generate
      working-directory: ./workflow
      run: go run . > workflow.yml

    - name: Relay: Save workflow
      run: relay workflow save cat-github-metrics -f workflow/workflow.yml
